# Generated by Django 3.2.21 on 2023-09-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Glover_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='consent',
        ),
    ]
